OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
  0%|          | 0/3 [00:00<?, ?it/s] 33%|███▎      | 1/3 [00:00<00:00,  4.99it/s]100%|██████████| 3/3 [00:00<00:00,  8.00it/s]100%|██████████| 3/3 [00:00<00:00,  7.54it/s]
eps 0.1: found 47 clusters with 1022 / 1421 points unassigned
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
eps 0.15: found 86 clusters with 531 / 1421 points unassigned
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86]
eps 0.2: found 61 clusters with 219 / 1421 points unassigned
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61]
Traceback (most recent call last):
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'frame'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fs02/rl54/Abi/platelet-analysis/massive/M3_cluster_platelets_0.py", line 58, in <module>
    plot_clusters(df, col, umap_cols, save=sp, show=False, size=(10, 10))
  File "/fs02/rl54/Abi/platelet-analysis/src/plateletanalysis/analysis/clustering.py", line 227, in plot_clusters
    sub_df = df[(df['frame'] >= frame_range[0]) & (df['frame'] < frame_range[1])]
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'frame'
